version: '2'

services:
  redis-1:
    image: redis
    ports:
      - 6379:6379

  redis-2:
    image: redis
    ports:
      - 6380:6379

  redis-3:
    image: redis
    ports:
      - 6381:6379

  redis-4:
    image: redis
    ports:
      - 6382:6379
